<script lang="ts" setup>
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { bn } from '../locals/home/bn.js'

const { t, locale, setLocaleMessage } = useI18n({ useScope: 'global' })

const langs = [
    { name: 'English', code: 'en' },
    { name: 'বাংলা', code: 'bn' }
]
const selectedLocalCode = ref('en')

function changeLang(code: string) {
    selectedLocalCode.value = code
    setLocaleMessage('bn', bn.bn)
    locale.value = code
}
</script>

<template>
    <v-menu transition="slide-x-transition">
        <template v-slot:activator="{ props }">
            <Transition>
                <v-btn class="btn-anim" size="small" v-bind="props" variant="tonal">
                    <span class="material-symbols-outlined" style="font-size: 14px">
                        translate
                    </span>
                    <span class="ml-2">{{ selectedLocalCode.toUpperCase() }}</span>
                </v-btn>
            </Transition>
        </template>

        <v-list>
            <template v-for="(lang, i) in langs" :key="i">
                <v-list-item :active="lang.code === selectedLocalCode">
                    <button @click="changeLang(lang.code)">{{ lang.name }}</button>
                </v-list-item>
            </template>
        </v-list>
    </v-menu>
</template>

<style>
.v-enter-from {
    animation: btn-anim 0.8s both;
    animation-delay: 5s;
}
.v-enter-to {
    animation: btn-anim 0.8s reverse;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-12-26 12:7:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@keyframes btn-anim {
    0%,
    100% {
        transform: translateX(0);
        transform-origin: 50% 50%;
    }
    15% {
        transform: translateX(-30px) rotate(-6deg);
    }
    30% {
        transform: translateX(15px) rotate(6deg);
    }
    45% {
        transform: translateX(-15px) rotate(-3.6deg);
    }
    60% {
        transform: translateX(9px) rotate(2.4deg);
    }
    75% {
        transform: translateX(-6px) rotate(-1.2deg);
    }
}
</style>